### ISSUE TITLE
stripeId: null in reader object

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#15] opened 2020-06-07 03:50 UTC
I can discover and connect to my BBPOS Chipper 2X BT now but the ID of the reader is not returned.  I noticed in the reader object thats returned after being discovered/connected has a property called `stripeId` which is set to `null`.  Is this intentional? Is there anyway you can include the actual ID of this reader from Stripe?

**Comment by nprail** [comment] 2020-06-07 18:48
I believe that the `stripeId` is only for the Verifone P400 but I can't find where I read that. It was added in v1.1.0 of the SDK which mostly just adds support for the P400. 

https://github.com/stripe/stripe-terminal-ios/releases/tag/v1.1.0

If you simulate a P400, do you get the ID?

**Comment by kyleabens** [comment] 2020-06-07 19:05
Ah I forgot they added support to the iOS SDK for the Verifone P400.  I integrated the Stripe Terminal javascript SDK a while back and use that along side this plugin to connect to the Verifone P400.  I can confirm that with the javascript SDK discoverReaders() returns an array of [Reader Objects](https://stripe.com/docs/api/terminal/readers/object) which includes an ID.

**Comment by nprail** [comment] 2020-06-08 14:36
If you simulate P400 discovery with the Capacitor plugin, does the response have the `stripeId`?

**Comment by nprail** [comment] 2020-06-26 17:31
Closing since this is expected behavior.

**Closed by nprail** 2020-06-26 17:31 UTC
