### ISSUE TITLE
Support for Wisepad 3

### ISSUE THREAD

**Issue by milad-alizadeh** [eventOneHQ/capacitor-stripe-terminal#64] opened 2021-09-01 19:58 UTC
Hi does this support the Stripe Wisepad 3 terminal? If not is there a way to get this working with some custom code?
https://stripe.com/docs/terminal/readers/bbpos-wisepad3

**Comment by nprail** [comment] 2021-09-01 20:14
@milad-alizadeh I am currently working on upgrading this plugin to Stripe Terminal v2 (#54) which will include support for the WisePad 3. That should be done in a few weeks. 

If you need it faster than a few weeks, I _may_ be able to simply add `WisePad3` to the `DeviceType` enum. I think Stripe Terminal v1 supports it too.

**Comment by nprail** [comment] 2021-09-01 20:25
I added `WisePad3` to the `DeviceType` enum in a new branch. In theory, it should just work. 

You can try it out by following these steps. If it works, let me know and I'll release it on v1. 
```bash
# clone the repo
git clone https://github.com/eventOneHQ/capacitor-stripe-terminal.git
cd capacitor-stripe-terminal

# checkout the branch
git checkout add-wisepad3

# link and build
npm link
npm install
npm run build

# then in your project link it
npm link capacitor-stripe-terminal

# and finally, build and run your project
```

**Comment by milad-alizadeh** [comment] 2021-09-02 03:46
You're a legend dude. Thank you very much!

**Comment by milad-alizadeh** [comment] 2021-09-02 14:21
I'm getting an error currently when I use npm link. 

```
/capacitor-stripe-terminal/android/src/main/java/io/event1/capacitorstripeterminal/StripeTerminal.java:136: error: cannot access AppCompatActivity
        getBridge().getActivity(),
                               ^
  class file for androidx.appcompat.app.AppCompatActivity not found
```

**Comment by milad-alizadeh** [comment] 2021-09-02 19:08
So I successfully added all the above and ran the app. So I've got this in my code
```
    scan () {
      // Start scanning for readers
      // capacitor-stripe-terminal uses Observables for any data streams
      // To stop scanning, unsubscribe from the Observable.
      // You must connect to a reader while scanning
      this.terminal
        .discoverReaders({
          simulated: true,
          deviceType: DeviceType.Chipper2X,
          discoveryMethod: DiscoveryMethod.BluetoothProximity,
        })
        .subscribe(readers => {
          if (readers.length) {
            this.newReaders = readers
            this.terminal
              .connectReader({
                serialNumber: readers[0].serialNumber,
                ipAddress: readers[0].ipAddress,
              })
              .then(connectedReader => {
                this.connectedReader = connectedReader
                console.log(connectedReader, 'connectedReader')
                // the reader is now connected and usable
              })
          }
        })
    },
```
So I get an error when trying this an physical iPad
<img width="1223" alt="Screenshot 2021-09-02 at 18 50 54" src="https://user-images.githubusercontent.com/9379343/131895204-4ed8fde1-1938-4ffd-b6a1-b06603c8d7ee.png">

I also get a compile error on Android. Have you come across any of these before?
<img width="1382" alt="Screenshot 2021-09-02 at 20 08 03" src="https://user-images.githubusercontent.com/9379343/131902317-b5fe2b8b-04a0-498f-ae48-ab81b34a3709.png">

**Comment by nprail** [comment] 2021-09-02 19:39
The Android build issue is a Capacitor 3 compatibility problem. `capacitor-stripe-terminal` v1 doesn't support Capacitor 3. That is also in the works as a part of version 2 of this plugin. 

The connection issue looks like it is caused by your token endpoint not serving a token correctly.

**Comment by nprail** [comment] 2021-09-02 19:43
You can install the v2 beta with NPM. That will get you Capacitor 3 support but not Stripe Terminal 2 support yet. I am making good progress on that, though. 
```bash
npm install capacitor-stripe-terminal@beta
```

**Comment by milad-alizadeh** [comment] 2021-09-02 20:24
Thanks a lot dude really appreciate it. You said a few weeks for the full version 2.0?

**Comment by milad-alizadeh** [comment] 2021-09-03 14:20
So I tried this code with a Wisepad3 and iPad:
```
      this.terminal
        .discoverReaders({
          simulated: false,
          deviceType: DeviceType.WisePad3, // 2
          discoveryMethod: DiscoveryMethod.BluetoothProximity,
        })
        .subscribe(readers => {
        ...
        })
```

In Xcode it throws this error

```
⚡️  To Native ->  StripeTerminal addListener 10341059
⚡️  To Native ->  StripeTerminal discoverReaders 10341060
[StripeTerminal] ⚠️  An integration error was detected in your app. This device type is not supported.(lldb) 
```

Is this because the SDK 1.0 does not support Wisepad3 or am I missing something?

**Comment by nprail** [comment] 2021-09-03 15:02
@milad-alizadeh Hmm, yeah, looks like v1 of the SDK doesn't actually support that reader. A little strange considering it's in the enum. 

v2 support is coming along quite nicely. I should have a beta out that supports iOS and _maybe_ Android next week.

**Comment by milad-alizadeh** [comment] 2021-09-03 16:19
Fantastic looking forward to it :)

**Comment by nprail** [comment] 2021-09-08 19:24
Stripe Terminal v2 is now supported on the beta tag!

```bash
npm install capacitor-stripe-terminal@beta
```

Closing this issue since it is available now. Let me know if you have any issues!

**Closed by nprail** 2021-09-08 19:24 UTC
Labels: enhancement

**Comment by milad-alizadeh** [comment] 2021-09-20 09:42
Amazing thanks :)
